# Generated by Django 3.2 on 2021-04-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('medicine_name', models.CharField(max_length=50)),
                ('mfg_date', models.DateField(verbose_name='Mfg Date (MM/DD/YYYY)')),
                ('exp_date', models.DateField(verbose_name='Exp Date (MM/DD/YYYY)')),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('medicine_name', models.CharField(max_length=50)),
                ('mfg_date', models.DateField(verbose_name='Mfg Date (MM/DD/YYYY)')),
                ('exp_date', models.DateField(verbose_name='Exp Date (MM/DD/YYYY)')),
                ('price', models.FloatField()),
                ('customer', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('purchase_date', models.DateField(verbose_name='Purchase Date (MM/DD/YYYY)')),
            ],
        ),
    ]
